# -*- coding: utf-8 -*-
"""Text_to_Speech.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bn_lHNtvQzbXn0_BjHr_i23hEaj7Egw-
"""

import streamlit as st
from gtts import gTTS
from io import BytesIO
import base64

def text_to_speech(text, lang='en'):
  tts = gTTS(text=text, lang=lang, slow=False)
  fp = BytesIO()
  tts.write_to_fp(fp)
  return fp

st.title("Text to Speech Converter")

text_input = st.text_area("Enter text:")

languages = {'English': 'en', 'French': 'fr', 'German': 'de','Italian': 'it', 'Hindi': 'hi', 'Telugu': 'te', 'Korean': 'ko'}

selected_language = st.selectbox("Select language:", list(languages.keys()))

if st.button("Convert to Speech"):
  # Convert text to Speech
  lang_code = languages[selected_language]
  speech_fp = text_to_speech(text_input, lang=lang_code)
  # Play the speech
  st.audio(speech_fp, format="audio/mpeg", start_time = 0)
  # Download link
  b64 = base64.b64encode(speech_fp.getvalue()).decode()
  href = f'<a href="data:audio/mpeg;base64,{b64}" download="speech.mp3">Download Audio</a>'
  st.markdown(href, unsafe_allow_html=True)

